version: '3.8'

services:
  frontend:
    image: halderson/tarefas_front
    container_name: frontend
    environment:
      - REACT_APP_URL_BACKEND=http://backend:5000/produtos
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: halderson/tarefas_back
    container_name: backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/tarefas
      - SERVER_PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:6.0.4
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: tarefas
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      
volumes:
  mongo_data: