apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
    app: tarefas-app
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30003
  selector:
    name: mongo-pod
    app: tarefas-app